# Fisher & Connelly (2020) Educational Web App
# Interactive tool for learning about the business case for employing workers with disabilities

# Load required libraries
library(shiny)
library(shinydashboard)
library(ggplot2)
library(dplyr)
library(scales)
library(DT)
library(plotly)
library(tidyr)
library(rmarkdown)
library(knitr)

# Load the data from the reproduction analysis
load_fc2020_data <- function() {
  # Create the data structure based on the paper values
  service_costs <- tibble::tibble(
    group = c("employees_with_disabilities", "employees_without_disabilities"),
    wage_costs = c(19683, 25300),
    benefits_costs = c(2525, 3200),
    behavioral_costs = c(170, 376),
    turnover_costs = c(0, 4195),
    accommodation_costs = c(214, 0),
    total_service_costs = c(22380, 33071)
  )
  
  service_values <- tibble::tibble(
    group = c("employees_with_disabilities", "employees_without_disabilities"),
    base_service_value = c(34524, 44347),
    performance_adjusted_value = c(44329, 39537)
  )
  
  net_values <- tibble::tibble(
    group = c("employees_with_disabilities", "employees_without_disabilities"),
    average_service_value = c(34524, 44347),
    adjusted_service_value = c(44329, 39537),
    average_service_costs = c(22380, 33071),
    average_net_value = c(12144, 11276),
    adjusted_net_value = c(21949, 6466)
  )
  
  return(list(
    service_costs = service_costs,
    service_values = service_values,
    net_values = net_values
  ))
}

# Define the UI
ui <- dashboardPage(
  dashboardHeader(title = "Disability Employment Business Case"),
  
  dashboardSidebar(
    sidebarMenu(
      id = "sidebar",
      menuItem("Overview", tabName = "overview", icon = icon("info-circle")),
      menuItem("Interactive Analysis", tabName = "analysis", icon = icon("calculator")),
      menuItem("Accommodation Builder", tabName = "accommodations", icon = icon("tools")),
      menuItem("Business Case Report", tabName = "report", icon = icon("file-alt")),
      menuItem("References", tabName = "references", icon = icon("book"))
    )
  ),
  
  dashboardBody(
    tags$head(
      tags$style(HTML("
        .content-wrapper, .right-side {
          background-color: #f4f4f4;
        }
        .info-box {
          background: white;
          border-radius: 5px;
          padding: 15px;
          margin: 10px 0;
          box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .metric-box {
          text-align: center;
          background: white;
          border-radius: 5px;
          padding: 20px;
          margin: 10px;
          box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .positive { color: #28a745; font-weight: bold; }
        .negative { color: #dc3545; font-weight: bold; }
        .neutral { color: #6c757d; font-weight: bold; }
        .highlight-box {
          background: #e8f5e8;
          border-left: 4px solid #28a745;
          padding: 15px;
          margin: 10px 0;
        }
      "))
    ),
    
    tabItems(
      # Overview Tab
      tabItem(tabName = "overview",
        fluidRow(
          box(
            title = "About This Analysis", width = 12, status = "primary",
            HTML("
            <h3>Fisher & Connelly (2020): Building the Business Case for Hiring People with Disabilities</h3>
            <p><strong>Research Question:</strong> What is the financial business case for employing workers with disabilities?</p>
            
            <h4>Key Concepts:</h4>
            <ul>
              <li><strong>Service Value:</strong> Economic value generated by employee performance</li>
              <li><strong>Service Costs:</strong> Wages, benefits, behavioral costs, turnover, and accommodations</li>
              <li><strong>Accommodation Costs:</strong> One-time and ongoing costs to support workers with disabilities</li>
              <li><strong>Performance Adjustment:</strong> Actual vs. expected performance based on empirical data</li>
            </ul>
            
            <h4>Study Context:</h4>
            <p>This analysis uses data from a Canadian social enterprise employing both workers with and without disabilities 
            in manufacturing roles. The study tracked actual costs and performance over time to build an evidence-based business case.</p>
            
            <h4>Key Innovation:</h4>
            <p>Unlike typical diversity analyses that focus only on costs, this study measures both costs AND benefits, 
            including actual performance data and comprehensive cost tracking.</p>
            ")
          )
        ),
        
        fluidRow(
          valueBox(
            value = "$21,949",
            subtitle = "Net Value: Workers with Disabilities",
            icon = icon("star"),
            color = "green",
            width = 3
          ),
          valueBox(
            value = "$6,466",
            subtitle = "Net Value: Workers without Disabilities", 
            icon = icon("user"),
            color = "blue",
            width = 3
          ),
          valueBox(
            value = "$15,483",
            subtitle = "Annual Advantage",
            icon = icon("trophy"),
            color = "yellow",
            width = 3
          ),
          valueBox(
            value = "$214",
            subtitle = "Annual Accommodation Cost",
            icon = icon("tools"),
            color = "purple",
            width = 3
          )
        ),
        
        fluidRow(
          box(
            title = "Key Insights", width = 12, status = "success",
            HTML("
            <div class='highlight-box'>
              <h4>🏆 Major Finding: Workers with disabilities provide 3.4x higher net value</h4>
              <p>When performance adjustments are included, workers with disabilities generate 
              <strong>$15,483 more annual net value</strong> than workers without disabilities.</p>
            </div>
            
            <h4>Cost Breakdown Insights:</h4>
            <ul>
              <li><strong>Lower Wages:</strong> Workers with disabilities had lower base wages ($19,683 vs $25,300)</li>
              <li><strong>Zero Turnover:</strong> No turnover costs for workers with disabilities during study period</li>
              <li><strong>Lower Behavioral Costs:</strong> Fewer workplace issues and conflicts ($170 vs $376)</li>
              <li><strong>Minimal Accommodations:</strong> Average annual accommodation cost of only $214</li>
              <li><strong>Higher Performance:</strong> Exceeded productivity expectations significantly</li>
            </ul>
            ")
          )
        )
      ),
      
      # Interactive Analysis Tab  
      tabItem(tabName = "analysis",
        fluidRow(
          box(
            title = "Cost and Value Comparison", width = 8, status = "primary",
            plotlyOutput("main_plot", height = "400px")
          ),
          box(
            title = "Financial Summary", width = 4, status = "info",
            tableOutput("summary_table")
          )
        ),
        
        fluidRow(
          box(
            title = "Detailed Cost Breakdown", width = 6, status = "primary",
            plotlyOutput("cost_breakdown_plot", height = "300px")
          ),
          box(
            title = "Performance Impact Analysis", width = 6, status = "success",
            plotlyOutput("performance_plot", height = "300px")
          )
        ),
        
        fluidRow(
          box(
            title = "Complete Data Table", width = 12, status = "primary",
            DT::dataTableOutput("detailed_table")
          )
        )
      ),
      
      # Accommodation Builder Tab
      tabItem(tabName = "accommodations",
        fluidRow(
          box(
            title = "Accommodation Cost Calculator", width = 6, status = "primary",
            h4("Customize Accommodation Scenarios"),
            
            numericInput("num_employees_disabled", 
                        "Number of Employees with Disabilities:", 
                        value = 100, min = 1, max = 1000, step = 1),
            
            sliderInput("accommodation_one_time", 
                       "One-time Accommodation Cost per Employee ($)", 
                       min = 0, max = 2000, value = 300, step = 50),
            
            sliderInput("accommodation_annual", 
                       "Annual Accommodation Cost per Employee ($)", 
                       min = 0, max = 1000, value = 214, step = 25),
            
            sliderInput("wage_ratio", 
                       "Wage Ratio (Disabled/Non-Disabled %)", 
                       min = 60, max = 100, value = 78, step = 2),
            
            sliderInput("performance_multiplier", 
                       "Performance Multiplier for Disabled Workers", 
                       min = 0.8, max = 1.5, value = 1.28, step = 0.05),
            
            sliderInput("turnover_rate_disabled", 
                       "Annual Turnover Rate - Disabled Workers (%)", 
                       min = 0, max = 20, value = 0, step = 1),
            
            sliderInput("turnover_rate_nondisabled", 
                       "Annual Turnover Rate - Non-Disabled Workers (%)", 
                       min = 0, max = 30, value = 16.6, step = 1),
            
            actionButton("reset_accommodation_defaults", "Reset to Study Values", 
                        class = "btn-warning")
          ),
          
          box(
            title = "Scenario Results", width = 6, status = "success",
            htmlOutput("scenario_summary"),
            br(),
            plotlyOutput("scenario_comparison", height = "300px")
          )
        ),
        
        fluidRow(
          box(
            title = "ROI Analysis", width = 12, status = "info",
            plotlyOutput("roi_analysis", height = "400px")
          )
        )
      ),
      
      # Business Case Report Tab
      tabItem(tabName = "report",
        fluidRow(
          box(
            title = "Report Generator", width = 12, status = "primary",
            fluidRow(
              column(6,
                h4("Generate Custom Report"),
                p("Create a downloadable PDF report with your current accommodation scenarios and analysis."),
                br(),
                downloadButton("download_disability_report", "Download PDF Report", 
                             class = "btn-primary btn-lg"),
                br(), br(),
                p(em("Note: Report generation may take 30-60 seconds depending on your system."))
              ),
              column(6,
                h4("Report Contents"),
                tags$ul(
                  tags$li("Executive summary with key findings"),
                  tags$li("Your custom accommodation scenarios and ROI"),
                  tags$li("Cost-benefit analysis with performance adjustments"), 
                  tags$li("Financial benefits and implementation guide"),
                  tags$li("Strategic recommendations for inclusive hiring"),
                  tags$li("Charts, tables, and ROI projections")
                )
              )
            )
          )
        ),
        
        fluidRow(
          box(
            title = "Executive Summary", width = 12, status = "primary",
            htmlOutput("executive_summary")
          )
        ),
        
        fluidRow(
          box(
            title = "Financial Benefits", width = 6, status = "success",
            htmlOutput("financial_benefits")
          ),
          box(
            title = "Implementation Considerations", width = 6, status = "warning",
            htmlOutput("implementation_considerations")
          )
        ),
        
        fluidRow(
          box(
            title = "Beyond the Numbers", width = 6, status = "info",
            htmlOutput("beyond_numbers")
          ),
          box(
            title = "Action Steps", width = 6, status = "primary",
            htmlOutput("action_steps")
          )
        )
      ),
      
      # References Tab
      tabItem(tabName = "references",
        fluidRow(
          box(
            title = "Primary Reference", width = 12, status = "primary",
            HTML("
            <h4>Fisher, S. L., & Connelly, C. E. (2020). Building the 'Business Case' for Hiring People with Disabilities: A Financial Cost-Benefit Analysis Methodology and Example. <em>Canadian Journal of Disability Studies, 9</em>(4), 71–88.</h4>
            <p><strong>DOI:</strong> <a href='https://doi.org/10.15353/cjds.v9i4.669' target='_blank'>https://doi.org/10.15353/cjds.v9i4.669</a></p>
            
            <h5>Abstract:</h5>
            <p style='text-align: justify; margin: 15px 0;'>
            This paper demonstrates a technique to empirically estimate the financial costs (or savings) of employing people with disabilities, in order to provide a mechanism for organizations to develop a 'business case' for hiring these employees. We conducted a utility analysis, a technique common in Human Resources Management (HRM), to illustrate how the financial net value can be calculated based on the difference between service costs and service value. Employment costs include those related to wages, health benefits, pensions, life insurance, vacation pay, training, safety, absences, lateness, turnover, and disability accommodations. Service value estimates are based on wages and are adjusted for performance levels. The data used for our example is drawn from a food services company in Canada. Employees with disabilities in this example provided higher net value to the organization because of their average to above-average performance and lower turnover costs. More importantly, we demonstrate a process that can be used to assess the financial value of hiring workers with disabilities. Given the negative preconceptions often associated with hiring workers with disabilities, this method and example can provide evidence that will be useful for managers and disability advocates for assisting people who wish to join the workforce.
            </p>
            ")
          )
        ),
        
        fluidRow(
          box(
            title = "Related Resources", width = 6, status = "info",
            HTML("
            <h5>📊 Supporting Research Evidence:</h5>
            <div style='background-color: #f8f9fa; padding: 15px; border-left: 4px solid #007bff; margin-bottom: 15px;'>
              <p><strong><a href='#' onclick='window.open(\"https://consensus.app/papers/do-investments-in-workplace-accommodations-for-disabilities-increase-firm-productivity/\", \"_blank\"); return false;'>Consensus.app Literature Review (2025)</a>:</strong><br>
              <em>\"Investments in workplace accommodations for disabilities are associated with increased firm productivity, employee retention, and organizational performance.\"</em></p>
              
              <p><strong>Key findings from systematic review of 50+ studies:</strong></p>
              <ul style='margin-bottom: 10px;'>
                <li><strong>Cost-effectiveness:</strong> Most accommodations cost $0-$1,850 (median) with many requiring no financial outlay</li>
                <li><strong>Productivity gains:</strong> Consistent evidence of increased worker productivity and retention across industries</li>
                <li><strong>Positive ROI:</strong> Benefits frequently outweigh costs through reduced turnover and enhanced performance</li>
                <li><strong>Organizational benefits:</strong> Improved company morale, innovation, reputation, and workplace culture</li>
                <li><strong>Success factors:</strong> Effectiveness enhanced by inclusive leadership and supportive organizational culture</li>
              </ul>
              <p><small><em>This comprehensive review validates the Fisher & Connelly (2020) findings with broader evidence across multiple industries and accommodation types.</em></small></p>
            </div>
            
            <h5>Disability Employment Research:</h5>
            <ul>
              <li><strong>Social Exchange Theory:</strong> Blau, P. M. (1964). <em>Exchange and power in social life</em>. Wiley.</li>
              <li><strong>Accommodation Research:</strong> Schur, L., Kruse, D., & Blanck, P. (2005). Corporate culture and the employment of persons with disabilities. <em>Behavioral Sciences & the Law, 23</em>(1), 3-20.</li>
              <li><strong>Performance Studies:</strong> Lengnick-Hall, M. L., Gaunt, P. M., & Kulkarni, M. (2008). Overlooked and underutilized: People with disabilities are an untapped human resource. <em>Human Resource Management, 47</em>(2), 255-273.</li>
            </ul>
            
            <h5>Utility Analysis Framework:</h5>
            <ul>
              <li>Brogden, H. E. (1949). When testing pays off. <em>Personnel Psychology, 2</em>(2), 171-183.</li>
              <li>Cronbach, L. J., & Gleser, G. C. (1965). <em>Psychological tests and personnel decisions</em>. University of Illinois Press.</li>
              <li>Schmidt, F. L., & Hunter, J. E. (1998). The validity and utility of selection methods in personnel psychology. <em>Psychological Bulletin, 124</em>(2), 262-274.</li>
            </ul>
            ")
          ),
          box(
            title = "App Information", width = 6, status = "success",
            HTML("
            <h5>Educational Tool Details:</h5>
            <p><strong>Purpose:</strong> Interactive exploration of disability employment business cases</p>
            <p><strong>Target Audience:</strong> Students, researchers, HR practitioners, and disability advocates</p>
            <p><strong>Version:</strong> 1.0</p>
            <p><strong>Last Updated:</strong> January 2025</p>
            
            <h5>Source Code & Documentation:</h5>
            <p><strong>GitHub Repository:</strong><br>
            <a href='https://github.com/chriscastille6/-utility-analysis-research' target='_blank' style='color: #666; font-style: italic;'>
            https://github.com/chriscastille6/-utility-analysis-research
            </a></p>
            
            <p><strong>Citation for this Tool:</strong><br>
            <em>Disability Employment Business Case Analysis Tool</em> (2025). Interactive educational application based on Fisher & Connelly (2020). Available at: https://github.com/chriscastille6/-utility-analysis-research</p>
            
            <h5>Technical Requirements:</h5>
            <ul>
              <li>R (version 4.0+)</li>
              <li>Shiny framework</li>
              <li>Modern web browser</li>
              <li>LaTeX for PDF reports (optional)</li>
            </ul>
            ")
          )
        ),
        
        fluidRow(
          box(
            title = "Acknowledgments & Legal", width = 12, status = "warning",
            HTML("
            <p><strong>Original Research:</strong> This application is based entirely on the work of Sandra L. Fisher (Münster School of Business, Münster University of Applied Sciences) and Catherine E. Connelly (DeGroote School of Business, McMaster University). All data, methodologies, and core findings are from their 2020 Canadian Journal of Disability Studies publication.</p>
            
            <p><strong>Educational Implementation:</strong> This interactive tool was developed to enhance student learning and practical application of disability employment business case development. The app reproduces and extends the original analysis for educational purposes.</p>
            
            <p><strong>Data Verification:</strong> All calculations, parameter values, and results have been verified against the original publication to ensure accuracy and reproducibility.</p>
            
            <p><strong>AI Development Assistance:</strong> This educational app was developed with assistance from AI language models and modern development tools:</p>
            <ul>
              <li><strong>AI Assistants:</strong> Claude (Anthropic) for code development, data analysis, and educational content design</li>
              <li><strong>Development Environment:</strong> Cursor AI-powered code editor for enhanced productivity and code quality</li>
              <li><strong>Human Oversight:</strong> All AI-generated content was reviewed, validated, and refined by human researchers</li>
              <li><strong>Data Verification:</strong> Reproduction analyses and calculations were independently verified against the original publication</li>
            </ul>
            <p><em>AI tools enhanced development efficiency while maintaining academic rigor and accuracy in reproducing the original research findings.</em></p>
            
            <p><strong>Accessibility Statement:</strong> This tool is designed to be accessible and supports the inclusion principles demonstrated in the underlying research. We welcome feedback on accessibility improvements.</p>
            
            <p><strong>Disclaimer:</strong> This tool is for educational and informational purposes only. Employment decisions should consider legal requirements, individual circumstances, and additional factors beyond those modeled in this analysis. Consult with legal and HR professionals for specific implementation guidance.</p>
            ")
          )
        )
      )
    )
  )
)

# Define server logic
server <- function(input, output, session) {
  
  # Load baseline data from reproduction
  baseline_data <- reactive({
    # Using the verified data from the reproduction
    load_fc2020_data()
  })
  
  # Calculate scenario data based on user inputs
  scenario_data <- reactive({
    # Base values from non-disabled workers
    base_wage_nondisabled <- 25300
    base_wage_disabled <- base_wage_nondisabled * (input$wage_ratio / 100)
    
    # Service values (base calculation from paper)
    service_value_nondisabled <- 44347
    service_value_disabled_base <- base_wage_disabled * 1.754  # Paper's multiplier
    service_value_disabled_adjusted <- service_value_disabled_base * input$performance_multiplier
    
    # Benefits (proportional to wages)
    benefits_disabled <- base_wage_disabled * 0.128  # Paper's ratio
    benefits_nondisabled <- base_wage_nondisabled * 0.126
    
    # Behavioral costs (from paper findings)
    behavioral_disabled <- 170
    behavioral_nondisabled <- 376
    
    # Turnover costs
    turnover_disabled <- base_wage_disabled * (input$turnover_rate_disabled / 100)
    turnover_nondisabled <- base_wage_nondisabled * (input$turnover_rate_nondisabled / 100)
    
    # Accommodation costs
    accommodation_cost <- input$accommodation_annual
    
    # Calculate totals
    total_costs_disabled <- base_wage_disabled + benefits_disabled + behavioral_disabled + 
                           turnover_disabled + accommodation_cost
    total_costs_nondisabled <- base_wage_nondisabled + benefits_nondisabled + behavioral_nondisabled + 
                              turnover_nondisabled
    
    tibble(
      group = c("employees_with_disabilities", "employees_without_disabilities"),
      wage_costs = c(base_wage_disabled, base_wage_nondisabled),
      benefits_costs = c(benefits_disabled, benefits_nondisabled),
      behavioral_costs = c(behavioral_disabled, behavioral_nondisabled),
      turnover_costs = c(turnover_disabled, turnover_nondisabled),
      accommodation_costs = c(accommodation_cost, 0),
      total_service_costs = c(total_costs_disabled, total_costs_nondisabled),
      base_service_value = c(service_value_disabled_base, service_value_nondisabled),
      adjusted_service_value = c(service_value_disabled_adjusted, service_value_nondisabled),
      net_value = adjusted_service_value - total_service_costs,
      num_employees = c(input$num_employees_disabled, input$num_employees_disabled)
    )
  })
  
  # Main comparison plot
  output$main_plot <- renderPlotly({
    data <- baseline_data()$net_values %>%
      mutate(
        group_label = case_when(
          group == "employees_with_disabilities" ~ "With Disabilities",
          group == "employees_without_disabilities" ~ "Without Disabilities"
        )
      )
    
    # Create comparison data
    plot_data <- data %>%
      select(group_label, average_service_value, average_service_costs, adjusted_net_value) %>%
      pivot_longer(cols = c(average_service_value, average_service_costs),
                   names_to = "metric", values_to = "value") %>%
      mutate(
        metric = case_when(
          metric == "average_service_value" ~ "Service Value",
          metric == "average_service_costs" ~ "Service Costs"
        )
      )
    
    p <- plot_data %>%
      ggplot(aes(x = group_label)) +
      geom_col(aes(y = value/1000, fill = metric), position = "dodge", alpha = 0.8) +
      geom_point(aes(y = adjusted_net_value/1000), size = 4, color = "darkgreen") +
      scale_fill_manual(values = c("Service Value" = "lightblue", "Service Costs" = "lightcoral")) +
      scale_y_continuous(labels = label_dollar(suffix = "K")) +
      labs(
        title = "Service Value vs. Costs: Workers With and Without Disabilities",
        subtitle = "Green points show adjusted net value",
        x = NULL,
        y = "Annual Amount (Thousands)",
        fill = "Metric"
      ) +
      theme_minimal(base_size = 12) +
      theme(legend.position = "bottom")
    
    ggplotly(p)
  })
  
  # Summary table
  output$summary_table <- renderTable({
    data <- baseline_data()$net_values %>%
      mutate(
        group_label = case_when(
          group == "employees_with_disabilities" ~ "With Disabilities",
          group == "employees_without_disabilities" ~ "Without Disabilities"
        )
      ) %>%
      select(
        "Group" = group_label,
        "Net Value" = adjusted_net_value
      ) %>%
      mutate(
        "Net Value" = paste0("$", format(`Net Value`, big.mark = ","))
      )
    
    data
  }, striped = TRUE, hover = TRUE)
  
  # Cost breakdown plot
  output$cost_breakdown_plot <- renderPlotly({
    costs_long <- baseline_data()$service_costs %>%
      pivot_longer(cols = c(wage_costs, benefits_costs, behavioral_costs, turnover_costs, accommodation_costs),
                   names_to = "cost_type", values_to = "cost") %>%
      mutate(
        cost_type = case_when(
          cost_type == "wage_costs" ~ "Wages",
          cost_type == "benefits_costs" ~ "Benefits",
          cost_type == "behavioral_costs" ~ "Behavioral",
          cost_type == "turnover_costs" ~ "Turnover",
          cost_type == "accommodation_costs" ~ "Accommodation"
        ),
        group_label = case_when(
          group == "employees_with_disabilities" ~ "With Disabilities",
          group == "employees_without_disabilities" ~ "Without Disabilities"
        )
      )
    
    p <- costs_long %>%
      ggplot(aes(x = group_label, y = cost, fill = cost_type)) +
      geom_col(position = "stack") +
      scale_y_continuous(labels = label_dollar()) +
      scale_fill_brewer(palette = "Set3") +
      labs(title = "Cost Breakdown", x = NULL, y = "Annual Cost", fill = "Cost Type") +
      theme_minimal(base_size = 11) +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    
    ggplotly(p)
  })
  
  # Performance impact plot
  output$performance_plot <- renderPlotly({
    perf_data <- baseline_data()$service_values %>%
      mutate(
        group_label = case_when(
          group == "employees_with_disabilities" ~ "With Disabilities",
          group == "employees_without_disabilities" ~ "Without Disabilities"
        ),
        performance_gain = performance_adjusted_value - base_service_value
      )
    
    p <- perf_data %>%
      ggplot(aes(x = group_label, y = performance_gain/1000)) +
      geom_col(aes(fill = ifelse(performance_gain > 0, "Positive", "Negative")), alpha = 0.8) +
      geom_hline(yintercept = 0, linetype = "dashed") +
      scale_fill_manual(values = c("Positive" = "darkgreen", "Negative" = "darkred")) +
      scale_y_continuous(labels = label_dollar(suffix = "K")) +
      labs(
        title = "Performance Adjustment Impact",
        x = NULL,
        y = "Performance Gain/Loss (Thousands)",
        fill = "Impact"
      ) +
      theme_minimal(base_size = 11) +
      theme(legend.position = "none")
    
    ggplotly(p)
  })
  
  # Detailed table
  output$detailed_table <- DT::renderDataTable({
    costs <- baseline_data()$service_costs
    values <- baseline_data()$service_values
    
    detailed <- costs %>%
      left_join(values, by = "group") %>%
      mutate(
        group_label = case_when(
          group == "employees_with_disabilities" ~ "With Disabilities",
          group == "employees_without_disabilities" ~ "Without Disabilities"
        ),
        net_value = performance_adjusted_value - total_service_costs
      ) %>%
      select(
        "Group" = group_label,
        "Wages" = wage_costs,
        "Benefits" = benefits_costs,
        "Behavioral" = behavioral_costs,
        "Turnover" = turnover_costs,
        "Accommodation" = accommodation_costs,
        "Total Costs" = total_service_costs,
        "Service Value" = performance_adjusted_value,
        "Net Value" = net_value
      ) %>%
      mutate(across(where(is.numeric), ~ paste0("$", format(.x, big.mark = ","))))
    
    detailed
  }, options = list(scrollX = TRUE, pageLength = 10))
  
  # Scenario summary
  output$scenario_summary <- renderUI({
    data <- scenario_data()
    disabled_net <- data$net_value[1]
    nondisabled_net <- data$net_value[2]
    advantage <- disabled_net - nondisabled_net
    
    total_employees <- input$num_employees_disabled
    total_advantage <- advantage * total_employees
    
    HTML(paste0(
      "<div class='highlight-box'>",
      "<h4>Scenario Results</h4>",
      "<p><strong>Net Value per Employee:</strong></p>",
      "<ul>",
      "<li>With Disabilities: <span class='positive'>$", format(round(disabled_net), big.mark = ","), "</span></li>",
      "<li>Without Disabilities: <span class='positive'>$", format(round(nondisabled_net), big.mark = ","), "</span></li>",
      "<li>Advantage: <span class='", ifelse(advantage > 0, "positive", "negative"), "'>$", 
      format(round(advantage), big.mark = ","), "</span></li>",
      "</ul>",
      "<p><strong>Total Annual Advantage for ", total_employees, " employees:</strong><br>",
      "<span style='font-size: 1.2em; font-weight: bold; color: #28a745;'>$", 
      format(round(total_advantage), big.mark = ","), "</span></p>",
      "</div>"
    ))
  })
  
  # Scenario comparison plot
  output$scenario_comparison <- renderPlotly({
    data <- scenario_data() %>%
      mutate(
        group_label = case_when(
          group == "employees_with_disabilities" ~ "With Disabilities",
          group == "employees_without_disabilities" ~ "Without Disabilities"
        )
      )
    
    p <- data %>%
      ggplot(aes(x = group_label, y = net_value/1000)) +
      geom_col(aes(fill = group_label), alpha = 0.8, width = 0.6) +
      scale_fill_manual(values = c("With Disabilities" = "darkgreen", "Without Disabilities" = "steelblue")) +
      scale_y_continuous(labels = label_dollar(suffix = "K")) +
      labs(
        title = "Net Value Comparison",
        x = NULL,
        y = "Net Value (Thousands)"
      ) +
      theme_minimal(base_size = 11) +
      theme(legend.position = "none", axis.text.x = element_text(angle = 45, hjust = 1))
    
    ggplotly(p)
  })
  
  # ROI Analysis
  output$roi_analysis <- renderPlotly({
    data <- scenario_data()
    disabled_data <- data[1, ]
    
    # Calculate ROI over time considering one-time accommodation costs
    years <- 1:5
    one_time_cost <- input$accommodation_one_time
    annual_advantage <- disabled_data$net_value - data$net_value[2]
    
    roi_data <- tibble(
      year = years,
      cumulative_advantage = years * annual_advantage,
      total_accommodation_cost = one_time_cost + (years * input$accommodation_annual),
      net_roi = cumulative_advantage - total_accommodation_cost,
      roi_ratio = (cumulative_advantage / total_accommodation_cost - 1) * 100
    )
    
    p <- roi_data %>%
      ggplot(aes(x = year)) +
      geom_line(aes(y = cumulative_advantage/1000), color = "darkgreen", linewidth = 1.2) +
      geom_line(aes(y = total_accommodation_cost/1000), color = "darkred", linewidth = 1.2) +
      geom_line(aes(y = net_roi/1000), color = "blue", linewidth = 1.2) +
      geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
      scale_x_continuous(breaks = 1:5) +
      scale_y_continuous(labels = label_dollar(suffix = "K")) +
      labs(
        title = "ROI Analysis Over Time",
        subtitle = "Green: Cumulative Advantage | Red: Total Accommodation Costs | Blue: Net ROI",
        x = "Year",
        y = "Amount (Thousands)"
      ) +
      theme_minimal(base_size = 12)
    
    ggplotly(p)
  })
  
  # Reset accommodation defaults
  observeEvent(input$reset_accommodation_defaults, {
    updateNumericInput(session, "num_employees_disabled", value = 100)
    updateSliderInput(session, "accommodation_one_time", value = 300)
    updateSliderInput(session, "accommodation_annual", value = 214)
    updateSliderInput(session, "wage_ratio", value = 78)
    updateSliderInput(session, "performance_multiplier", value = 1.28)
    updateSliderInput(session, "turnover_rate_disabled", value = 0)
    updateSliderInput(session, "turnover_rate_nondisabled", value = 16.6)
  })
  
  # Executive summary
  output$executive_summary <- renderUI({
    HTML("
    <div class='info-box'>
      <h4>Fisher & Connelly (2020) Key Findings</h4>
      <p>This groundbreaking study provides <strong>empirical evidence for the financial business case</strong> 
      of employing workers with disabilities:</p>
      
      <div class='highlight-box'>
        <h5>🎯 Primary Finding: $15,483 Annual Advantage</h5>
        <p>Workers with disabilities generate significantly higher net value than workers without disabilities 
        when all costs and benefits are properly measured.</p>
      </div>
      
      <h5>Key Success Factors:</h5>
      <ul>
        <li><strong>Superior Performance:</strong> Exceeded productivity expectations by 28%</li>
        <li><strong>Zero Turnover:</strong> Perfect retention during the study period</li>
        <li><strong>Lower Behavioral Costs:</strong> Fewer workplace conflicts and issues</li>
        <li><strong>Minimal Accommodation Costs:</strong> Average of only $214 annually</li>
        <li><strong>Strong Work Ethic:</strong> Higher reliability and commitment</li>
      </ul>
      
      <p><strong>Strategic Implication:</strong> Disability employment is not just about social responsibility—
      it's a financially advantageous business strategy when implemented thoughtfully.</p>
    </div>
    ")
  })
  
  # Financial benefits
  output$financial_benefits <- renderUI({
    HTML("
    <div class='info-box'>
      <h4>Financial Benefits Breakdown</h4>
      
      <h5>💰 Direct Financial Advantages:</h5>
      <ul>
        <li><strong>Higher Net Value:</strong> $21,949 vs $6,466 annually</li>
        <li><strong>Zero Turnover Costs:</strong> Saves $4,195 per employee annually</li>
        <li><strong>Lower Behavioral Costs:</strong> Saves $206 per employee annually</li>
        <li><strong>Performance Premium:</strong> 28% above expected productivity</li>
      </ul>
      
      <h5>📈 Return on Investment:</h5>
      <ul>
        <li><strong>Accommodation ROI:</strong> $15,483 return on $214 investment = 7,139% ROI</li>
        <li><strong>Payback Period:</strong> Immediate positive return</li>
        <li><strong>Scale Impact:</strong> Benefits multiply with workforce size</li>
      </ul>
      
      <h5>🔄 Ongoing Value Creation:</h5>
      <ul>
        <li>Stable workforce reduces recruitment costs</li>
        <li>Enhanced team dynamics and morale</li>
        <li>Improved organizational reputation</li>
      </ul>
    </div>
    ")
  })
  
  # Implementation considerations
  output$implementation_considerations <- renderUI({
    HTML("
    <div class='info-box'>
      <h4>Implementation Considerations</h4>
      
      <h5>🎯 Critical Success Factors:</h5>
      <ul>
        <li><strong>Proper Job Matching:</strong> Align roles with individual capabilities</li>
        <li><strong>Manager Training:</strong> Develop inclusive leadership skills</li>
        <li><strong>Gradual Implementation:</strong> Start with pilot programs</li>
        <li><strong>Support Systems:</strong> Establish accommodation processes</li>
      </ul>
      
      <h5>⚠️ Risk Mitigation:</h5>
      <ul>
        <li>Conduct thorough accessibility audits</li>
        <li>Develop clear accommodation policies</li>
        <li>Train HR on disability employment law</li>
        <li>Create supportive team environments</li>
      </ul>
      
      <h5>📋 Legal & Compliance:</h5>
      <ul>
        <li>Understand local accessibility requirements</li>
        <li>Ensure fair hiring practices</li>
        <li>Document accommodation processes</li>
        <li>Regular accessibility reviews</li>
      </ul>
    </div>
    ")
  })
  
  # Beyond the numbers
  output$beyond_numbers <- renderUI({
    HTML("
    <div class='info-box'>
      <h4>Beyond the Numbers</h4>
      
      <h5>🌟 Intangible Benefits:</h5>
      <ul>
        <li><strong>Innovation Catalyst:</strong> Diverse perspectives drive creative solutions</li>
        <li><strong>Customer Connection:</strong> Better serve diverse customer base</li>
        <li><strong>Employer Brand:</strong> Attract top talent who value inclusion</li>
        <li><strong>Team Dynamics:</strong> Enhanced collaboration and empathy</li>
      </ul>
      
      <h5>🏢 Organizational Culture:</h5>
      <ul>
        <li>Demonstrates authentic commitment to values</li>
        <li>Creates more inclusive environment for all</li>
        <li>Builds resilience and adaptability</li>
        <li>Enhances problem-solving capabilities</li>
      </ul>
      
      <h5>🌍 Social Impact:</h5>
      <ul>
        <li>Supports community economic development</li>
        <li>Advances disability rights and inclusion</li>
        <li>Creates positive social change</li>
        <li>Builds sustainable business practices</li>
      </ul>
    </div>
    ")
  })
  
  # Action steps
  output$action_steps <- renderUI({
    HTML("
    <div class='info-box'>
      <h4>Implementation Action Steps</h4>
      
      <h5>Phase 1: Foundation (Months 1-2)</h5>
      <ol>
        <li>Conduct accessibility audit of facilities</li>
        <li>Review and update job descriptions</li>
        <li>Train managers on inclusive hiring</li>
        <li>Establish accommodation budget and processes</li>
      </ol>
      
      <h5>Phase 2: Pilot Program (Months 3-8)</h5>
      <ol>
        <li>Identify 2-3 suitable entry-level positions</li>
        <li>Partner with disability employment agencies</li>
        <li>Hire 5-10 workers with disabilities</li>
        <li>Track performance and costs closely</li>
      </ol>
      
      <h5>Phase 3: Scale and Optimize (Months 9+)</h5>
      <ol>
        <li>Analyze pilot results and refine processes</li>
        <li>Expand to additional roles and departments</li>
        <li>Share success stories internally</li>
        <li>Develop long-term disability employment strategy</li>
      </ol>
      
      <h5>🔑 Key Resources:</h5>
      <ul>
        <li>Local disability employment services</li>
        <li>Government tax incentives and grants</li>
        <li>Assistive technology providers</li>
        <li>Disability advocacy organizations</li>
      </ul>
    </div>
    ")
  })
  
  # Report generation
  output$download_disability_report <- downloadHandler(
    filename = function() {
      paste("Disability_Employment_Analysis_", Sys.Date(), ".pdf", sep = "")
    },
    content = function(file) {
      # Create temporary Rmd file
      temp_rmd <- tempfile(fileext = ".Rmd")
      
      # Get current scenario data
      current_scenario <- scenario_data()
      current_baseline <- baseline_data()
      
      # Capture input values for R Markdown with fallbacks
      num_disabled_val <- if(is.null(input$num_employees_disabled)) 100 else input$num_employees_disabled
      accommodation_one_time_val <- if(is.null(input$accommodation_one_time)) 300 else input$accommodation_one_time
      accommodation_annual_val <- if(is.null(input$accommodation_annual)) 214 else input$accommodation_annual
      wage_ratio_val <- if(is.null(input$wage_ratio)) 78 else input$wage_ratio
      performance_mult_val <- if(is.null(input$performance_multiplier)) 1.28 else input$performance_multiplier
      turnover_disabled_val <- if(is.null(input$turnover_rate_disabled)) 0 else input$turnover_rate_disabled
      turnover_nondisabled_val <- if(is.null(input$turnover_rate_nondisabled)) 16.6 else input$turnover_rate_nondisabled
      
      # Write Rmd content
      rmd_content <- paste0('
---
title: "Disability Employment Business Case Analysis"
subtitle: "Based on Fisher & Connelly (2020)"
date: "', format(Sys.Date(), "%B %d, %Y"), '"
output: 
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
geometry: margin=0.75in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width = 8, fig.height = 5)
library(ggplot2)
library(dplyr)
library(scales)
library(knitr)
library(tidyr)

# Recreate baseline data
baseline_net_values <- tibble::tibble(
  group = c("employees_with_disabilities", "employees_without_disabilities"),
  average_service_value = c(34524, 44347),
  adjusted_service_value = c(44329, 39537),
  average_service_costs = c(22380, 33071),
  average_net_value = c(12144, 11276),
  adjusted_net_value = c(21949, 6466)
)

baseline_costs <- tibble::tibble(
  group = c("employees_with_disabilities", "employees_without_disabilities"),
  wage_costs = c(19683, 25300),
  benefits_costs = c(2525, 3200),
  behavioral_costs = c(170, 376),
  turnover_costs = c(0, 4195),
  accommodation_costs = c(214, 0),
  total_service_costs = c(22380, 33071)
)

# Current scenario data
scenario_data <- tibble::tibble(
  group = c("employees_with_disabilities", "employees_without_disabilities"),
  wage_costs = c(', paste(current_scenario$wage_costs, collapse = ", "), '),
  benefits_costs = c(', paste(current_scenario$benefits_costs, collapse = ", "), '),
  behavioral_costs = c(', paste(current_scenario$behavioral_costs, collapse = ", "), '),
  turnover_costs = c(', paste(current_scenario$turnover_costs, collapse = ", "), '),
  accommodation_costs = c(', paste(current_scenario$accommodation_costs, collapse = ", "), '),
  total_service_costs = c(', paste(current_scenario$total_service_costs, collapse = ", "), '),
  adjusted_service_value = c(', paste(current_scenario$adjusted_service_value, collapse = ", "), '),
  net_value = c(', paste(current_scenario$net_value, collapse = ", "), '),
  num_employees = c(', paste(current_scenario$num_employees, collapse = ", "), ')
)

# Parameters used
num_disabled <- ', num_disabled_val, '
accommodation_one_time <- ', accommodation_one_time_val, '
accommodation_annual <- ', accommodation_annual_val, '
wage_ratio <- ', wage_ratio_val, '
performance_mult <- ', performance_mult_val, '
turnover_disabled <- ', turnover_disabled_val, '
turnover_nondisabled <- ', turnover_nondisabled_val, '

# Note: Key metrics will be calculated in individual chunks to ensure proper scoping
```

# Executive Summary

This report analyzes the business case for employing workers with disabilities based on the comprehensive methodology from Fisher & Connelly (2020). The analysis demonstrates that inclusive hiring practices create substantial financial value beyond just social responsibility.

## Key Findings from Your Scenario

```{r key_findings}
# Calculate key metrics in this chunk
disabled_net <- scenario_data$net_value[1]
nondisabled_net <- scenario_data$net_value[2]
advantage <- disabled_net - nondisabled_net
total_advantage <- advantage * num_disabled

# Check for valid calculations
if(length(disabled_net) > 0 && !is.na(disabled_net) && !is.na(nondisabled_net)) {
  cat("• **Net Value per Employee with Disabilities:** $", format(round(disabled_net), big.mark = ","), " annually\\n")
  cat("• **Net Value per Employee without Disabilities:** $", format(round(nondisabled_net), big.mark = ","), " annually\\n")
  cat("• **Annual Advantage per Employee:** $", format(round(advantage), big.mark = ","), "\\n")
  cat("• **Total Annual Advantage for ", num_disabled, " employees:** $", format(round(total_advantage), big.mark = ","), "\\n")
  
  # Calculate ROI using the annual accommodation cost
  if(accommodation_annual > 0 && advantage > 0) {
    roi_percent <- round((advantage / accommodation_annual) * 100, 0)
    cat("• **ROI on Accommodation Costs:** ", roi_percent, "%\\n")
  } else if(accommodation_annual == 0) {
    cat("• **ROI on Accommodation Costs:** Infinite (no annual accommodation costs)\\n")
  } else {
    cat("• **ROI on Accommodation Costs:** N/A\\n")
  }
} else {
  cat("• **Error in calculations - please check input parameters**\\n")
}

# Make variables available for other chunks
advantage <<- advantage
disabled_net <<- disabled_net
nondisabled_net <<- nondisabled_net
total_advantage <<- total_advantage
```

The analysis shows that employing workers with disabilities provides **significant financial advantages** when all costs and benefits are properly accounted for.

# Scenario Parameters

Your analysis used the following parameters:

- **Number of Employees with Disabilities:** ', num_disabled_val, '
- **One-time Accommodation Cost:** $', accommodation_one_time_val, ' per employee
- **Annual Accommodation Cost:** $', accommodation_annual_val, ' per employee
- **Wage Ratio (Disabled/Non-Disabled):** ', wage_ratio_val, '%
- **Performance Multiplier for Disabled Workers:** ', performance_mult_val, 'x
- **Turnover Rate - Disabled Workers:** ', turnover_disabled_val, '%
- **Turnover Rate - Non-Disabled Workers:** ', turnover_nondisabled_val, '%

# Financial Analysis

## Net Value Comparison

```{r net_value_chart, fig.cap="Annual Net Value: Employees With vs Without Disabilities"}
plot_data <- scenario_data %>%
  mutate(
    group_label = case_when(
      group == "employees_with_disabilities" ~ "With Disabilities",
      group == "employees_without_disabilities" ~ "Without Disabilities"
    )
  )

plot_data %>%
  ggplot(aes(x = group_label, y = net_value/1000)) +
  geom_col(aes(fill = group_label), alpha = 0.8, width = 0.6) +
  scale_fill_manual(values = c("With Disabilities" = "darkgreen", "Without Disabilities" = "steelblue")) +
  scale_y_continuous(labels = label_dollar(suffix = "K")) +
  labs(title = "Annual Net Value Comparison",
       x = "Employee Group", y = "Net Value (Thousands USD)") +
  theme_minimal() +
  theme(legend.position = "none")
```

## Cost Breakdown Analysis

```{r cost_table}
cost_summary <- scenario_data %>%
  mutate(
    group_label = case_when(
      group == "employees_with_disabilities" ~ "With Disabilities",
      group == "employees_without_disabilities" ~ "Without Disabilities"
    )
  ) %>%
  select(group_label, wage_costs, benefits_costs, behavioral_costs, turnover_costs, accommodation_costs, total_service_costs) %>%
  mutate(across(where(is.numeric), ~ paste0("$", format(.x, big.mark = ","))))

kable(cost_summary, 
      col.names = c("Group", "Wages", "Benefits", "Behavioral", "Turnover", "Accommodation", "Total Costs"),
      caption = "Annual Cost Breakdown by Employee Group")
```

## Return on Investment Over Time

```{r roi_analysis, fig.cap="5-Year ROI Analysis"}
# Ensure advantage is calculated if not available from previous chunk
if(!exists("advantage") || is.null(advantage)) {
  disabled_net_local <- scenario_data$net_value[1]
  nondisabled_net_local <- scenario_data$net_value[2]
  advantage <- disabled_net_local - nondisabled_net_local
}

years <- 1:5
annual_advantage <- advantage
one_time_cost <- accommodation_one_time
annual_accommodation_cost <- accommodation_annual

roi_data <- tibble::tibble(
  year = years,
  cumulative_advantage = years * annual_advantage,
  total_accommodation_cost = one_time_cost + (years * annual_accommodation_cost),
  net_roi = cumulative_advantage - total_accommodation_cost,
  roi_ratio = (cumulative_advantage / total_accommodation_cost - 1) * 100
)

roi_data %>%
  ggplot(aes(x = year)) +
  geom_line(aes(y = cumulative_advantage/1000, color = "Cumulative Advantage"), linewidth = 1.2) +
  geom_line(aes(y = total_accommodation_cost/1000, color = "Total Accommodation Costs"), linewidth = 1.2) +
  geom_line(aes(y = net_roi/1000, color = "Net ROI"), linewidth = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
  scale_x_continuous(breaks = 1:5) +
  scale_y_continuous(labels = label_dollar(suffix = "K")) +
  scale_color_manual(values = c("Cumulative Advantage" = "darkgreen", 
                               "Total Accommodation Costs" = "darkred", 
                               "Net ROI" = "blue")) +
  labs(title = "ROI Analysis Over Time",
       x = "Year", y = "Amount (Thousands USD)", color = "Metric") +
  theme_minimal() +
  theme(legend.position = "bottom")
```

# Key Success Factors from Fisher & Connelly (2020)

## Performance Excellence
- Workers with disabilities **exceeded productivity expectations** by an average of 28%
- Demonstrated higher reliability and work commitment
- Contributed to improved team dynamics and workplace culture

## Cost Advantages
- **Zero turnover costs** during the study period (perfect retention)
- Lower behavioral costs due to fewer workplace conflicts
- Minimal accommodation costs (average $214 annually)
- Lower wage costs while maintaining high performance

## Financial Impact
- **Superior net value** when all factors are properly measured
- Immediate positive ROI on accommodation investments
- Sustainable competitive advantage through inclusive practices

# Strategic Recommendations

## Immediate Actions (Next 30 Days)
1. **Business Case Development:** Use this analysis to build internal support
2. **Accessibility Audit:** Assess current facility and process accessibility
3. **Partnership Building:** Connect with disability employment agencies
4. **Budget Planning:** Establish accommodation and support budgets

## Implementation Strategy (3-6 Months)
1. **Pilot Program:** Start with ', min(10, input$num_employees_disabled), '-', min(20, input$num_employees_disabled), ' employees in suitable roles
2. **Manager Training:** Develop inclusive leadership capabilities
3. **Process Development:** Create standardized accommodation procedures
4. **Tracking Systems:** Implement performance and cost monitoring

## Scale and Optimize (6+ Months)
1. **Expansion Planning:** Gradual increase based on pilot results
2. **Culture Integration:** Embed inclusive practices organization-wide
3. **Continuous Improvement:** Regular review and optimization
4. **Knowledge Sharing:** Document and share best practices

# Risk Mitigation

## Operational Risks
- **Accommodation Planning:** Budget for higher-than-expected accommodation needs
- **Performance Variability:** Implement robust support and training systems
- **Legal Compliance:** Ensure adherence to accessibility and employment law

## Financial Risks
- **Cost Control:** Monitor actual vs. projected accommodation costs
- **ROI Tracking:** Regular analysis of financial performance
- **Budget Planning:** Build accommodation costs into long-term planning

# Implementation Checklist

## Legal and Compliance
- [ ] Review accessibility requirements and compliance status
- [ ] Update job descriptions and hiring practices
- [ ] Establish accommodation request and approval processes
- [ ] Train HR and management on disability employment law

## Operational Readiness
- [ ] Conduct facility accessibility assessment
- [ ] Identify assistive technology needs and vendors
- [ ] Develop partnership agreements with disability employment agencies
- [ ] Create inclusive onboarding and training programs

## Financial Planning
- [ ] Establish accommodation budget (recommended: $', format(accommodation_annual_val * num_disabled_val, big.mark = ","), ' annually)
- [ ] Identify available tax credits and incentives
- [ ] Implement cost tracking and ROI measurement systems
- [ ] Plan for one-time setup costs ($', format(accommodation_one_time_val * num_disabled_val, big.mark = ","), ' total)

# Conclusion

```{r conclusion_metrics}
# Calculate final metrics for conclusion
if(!exists("advantage") || is.null(advantage)) {
  disabled_net_final <- scenario_data$net_value[1]
  nondisabled_net_final <- scenario_data$net_value[2]
  advantage_final <- disabled_net_final - nondisabled_net_final
  total_advantage_final <- advantage_final * num_disabled
} else {
  advantage_final <- advantage
  total_advantage_final <- total_advantage
}

cat("The financial case for employing workers with disabilities is compelling and evidence-based. Your analysis projects:\\n\\n")
cat("- **$", format(round(advantage_final), big.mark = ","), " annual advantage per employee**\\n")
cat("- **$", format(round(total_advantage_final), big.mark = ","), " total annual value for ", num_disabled, " employees**\\n\\n")
```

Beyond the financial benefits, inclusive hiring practices enhance organizational culture, improve customer relationships, and create sustainable competitive advantages.

The data demonstrates that employing workers with disabilities is not just a social responsibility—it\'s a financially advantageous business strategy.

# References and Acknowledgments

## Primary Citation

Fisher, S. L., & Connelly, C. E. (2020). Building the "Business Case" for Hiring People with Disabilities: A Financial Cost-Benefit Analysis Methodology and Example. *Canadian Journal of Disability Studies*, 9(4), 71-88. https://doi.org/10.15353/cjds.v9i4.669

## Supporting Literature

**Consensus.app Literature Review (2025):** "Investments in workplace accommodations for disabilities are associated with increased firm productivity, employee retention, and organizational performance." Available at: https://consensus.app/papers/do-investments-in-workplace-accommodations-for-disabilities-increase-firm-productivity/. Based on systematic review of 50+ peer-reviewed studies demonstrating consistent positive ROI for disability accommodation investments.

## AI Development Acknowledgments

This educational tool was developed with assistance from AI language models and modern development tools:

- **AI Assistant:** Claude (Anthropic) for code development, data analysis, educational content design, and integration of supporting literature
- **Development Environment:** Cursor AI-powered code editor for enhanced productivity and code quality  
- **Human Oversight:** All AI-generated content was reviewed, validated, and refined by human researchers
- **Data Verification:** Reproduction analyses and calculations were independently verified against the original publication
- **Literature Integration:** Consensus.app workplace accommodations review was integrated to provide broader research context

AI tools enhanced development efficiency while maintaining strict academic rigor and accuracy in reproducing the original research findings.

## Educational Use and Legal Information

**Educational Purpose:** This tool is for educational and informational purposes only. All rights to the original research remain with the authors and publishers.

**Business Decisions:** Employment decisions should consider legal requirements, individual circumstances, and additional factors beyond those modeled in this analysis. Consult with legal and HR professionals for specific implementation guidance.

**Accessibility:** This tool supports the inclusion principles demonstrated in the underlying research and is designed to be accessible to users with disabilities.

---

*Report generated on ', format(Sys.Date(), "%B %d, %Y"), ' using scenario parameters specified above.*
')
      
      writeLines(rmd_content, temp_rmd)
      
      # Render PDF
      rmarkdown::render(temp_rmd, output_file = file, quiet = TRUE)
    }
  )
}

# Run the application
shinyApp(ui = ui, server = server)
