% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Extending Utility Analysis: The Evolution of the Latham \& Whyte Case},
  pdfauthor={Utility Analysis Research Project},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Extending Utility Analysis: The Evolution of the Latham \& Whyte
Case}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Comparing Traditional, Sturman (2000), and Star Performer
Approaches}
\author{Utility Analysis Research Project}
\date{2025-06-21}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\section{Executive Summary}\label{executive-summary}

This report examines how methodological advances in utility analysis
affect the interpretation of the classic Latham \& Whyte (1994) budget
analyst selection case. We compare four approaches:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Traditional utility analysis} using the
  Brogden-Cronbach-Gleser model
\item
  \textbf{Sturman (2000) Monte Carlo adjustments} accounting for
  realistic constraints
\item
  \textbf{Star performer adjustments} based on Joo et al.~(2022)
  methodology
\item
  \textbf{Combined approach} integrating both Sturman and star performer
  insights
\end{enumerate}

\textbf{Key Findings:}

\begin{itemize}
\tightlist
\item
  Traditional utility analysis estimates \textbf{\$112,258,934} in total
  value
\item
  Sturman adjustments reduce this to \textbf{\$72,968,307} (35\%
  reduction)
\item
  Star performer recognition increases value to \textbf{\$308,928,370}
  (175\% increase)
\item
  The combined realistic approach yields \textbf{\$247,142,696} (140\%
  increase)
\end{itemize}

The analysis demonstrates that while traditional utility analysis may
overestimate benefits, the recognition of star performers more than
compensates for these limitations, suggesting that high-quality
selection programs remain highly valuable investments.

\section{Background}\label{background}

\subsection{The Latham \& Whyte (1994)
Case}\label{the-latham-whyte-1994-case}

The Latham \& Whyte case study represents one of the most cited examples
in personnel selection utility analysis. It examined the financial
impact of implementing a cognitive ability test for selecting budget
analysts in a government agency.

\subsubsection{Case Parameters}\label{case-parameters}

\begin{longtable}[t]{>{\raggedright\arraybackslash}p{3cm}>{\raggedright\arraybackslash}p{2.5cm}NANANANA>{}p{3cm}}
\caption{\label{tab:case-parameters}Latham & Whyte (1994) Case Study Parameters}\\
\toprule
Parameter & Value\\
\midrule
Position & Budget Analyst\\
Organization & Government Agency\\
Candidates Selected & 618\\
Total Applicants & 12,360\\
Selection Ratio & 5\%\\
\addlinespace
Test Validity & 0.76\\
Mean Salary & \$29,000\\
Cost per Applicant & \$10\\
Time Horizon & 10 years\\
\bottomrule
\end{longtable}

\subsection{Methodological Evolution}\label{methodological-evolution}

\subsubsection{Traditional Utility
Analysis}\label{traditional-utility-analysis}

The traditional approach, based on the Brogden-Cronbach-Gleser model,
uses the formula:

\[U = N_s \times SDy \times r \times \frac{\phi}{p} \times T - N_a \times C_a\]

Where: - \(N_s\) = number selected - \(SDy\) = standard deviation of
performance in dollars (40\% of mean salary) - \(r\) = validity
coefficient - \(\phi\) = ordinate of normal curve at selection ratio -
\(p\) = selection ratio - \(T\) = time horizon - \(N_a\) = number of
applicants - \(C_a\) = cost per applicant

\subsubsection{Sturman (2000)
Contributions}\label{sturman-2000-contributions}

Sturman's Monte Carlo analysis revealed that traditional utility
analysis often overestimates benefits due to:

\begin{itemize}
\tightlist
\item
  \textbf{Range restriction effects} not fully accounted for
\item
  \textbf{Validity shrinkage} in operational settings
\item
  \textbf{Unrealistic assumptions} about performance distributions
\item
  \textbf{Sampling variability} in parameter estimates
\end{itemize}

\subsubsection{Star Performer Recognition (Joo et al.,
2022)}\label{star-performer-recognition-joo-et-al.-2022}

Recent research recognizes that job performance follows heavy-tailed
distributions where star performers create disproportionate value. The
key insight is adjusting SDy using:

\[SDy_{star} = 2.75 \times SDy_{traditional} = 2.75 \times (0.40 \times \text{mean salary}) = 1.1 \times \text{mean salary}\]

This adjustment is based on Burke \& Frederick's (1986) empirical
finding that the ratio of SDy to SDo averages 2.75 across occupations.

\section{Comparative Analysis}\label{comparative-analysis}

\subsection{Results Summary}\label{results-summary}

\begin{longtable}[t]{>{\raggedright\arraybackslash}p{3cm}>{\raggedright\arraybackslash}p{2.5cm}llll>{\raggedright\arraybackslash}p{3cm}}
\caption{\label{tab:results-table}Comparative Results: Four Approaches to Utility Analysis}\\
\toprule
Approach & SDy Method & SDy Value & Total Utility & Per-Hire Value & Change from Traditional & Key Assumption\\
\midrule
Traditional (Brogden-Cronbach-Gleser) & 40\% of mean salary & \$11,600 & \$112,258,934 & \$181,649 & Baseline & Normal performance distribution\\
Sturman (2000) Monte Carlo Adjusted & 40\% with Monte Carlo corrections & \$11,600 & \$72,968,307 & \$118,072 & -35\% & Range restriction \& validity shrinkage\\
Star Performer (Joo et al. 2022) & 1.1 × mean salary (global procedure) & \$31,900 & \$308,928,370 & \$499,884 & +175.2\% & Heavy-tailed performance distribution\\
Combined (Sturman + Star Power) & 1.1 × salary with corrections & \$31,900 & \$247,142,696 & \$399,907 & +120.2\% & Realistic constraints + star recognition\\
\bottomrule
\end{longtable}

\subsection{Visual Comparison}\label{visual-comparison}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={Total Utility Estimates by Approach}]{latham_whyte_comprehensive_report_files/figure-latex/utility-comparison-plot-1.pdf}}
\caption{Total Utility Estimates by Approach}
\end{figure}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={Per-Hire Value by Approach}]{latham_whyte_comprehensive_report_files/figure-latex/per-hire-comparison-plot-1.pdf}}
\caption{Per-Hire Value by Approach}
\end{figure}

\section{Detailed Analysis}\label{detailed-analysis}

\subsection{Traditional Approach}\label{traditional-approach}

The traditional Brogden-Cronbach-Gleser model yields:

\begin{itemize}
\tightlist
\item
  \textbf{Total Utility:} \$112,258,934
\item
  \textbf{Per-Hire Value:} \$181,649
\item
  \textbf{SDy Estimate:} \$11,600 (40\% of mean salary)
\end{itemize}

This represents the baseline estimate using classical utility analysis
assumptions of normal performance distributions and stable validity
coefficients.

\subsection{Sturman (2000) Monte Carlo
Adjustments}\label{sturman-2000-monte-carlo-adjustments}

Sturman's analysis suggests traditional estimates are often inflated.
Applying a conservative 35\% reduction:

\begin{itemize}
\tightlist
\item
  \textbf{Adjusted Total Utility:} \$72,968,307
\item
  \textbf{Reduction from Traditional:} \$39,290,627
\item
  \textbf{Key Insight:} Range restriction and validity shrinkage
  significantly impact real-world utility
\end{itemize}

The reduction reflects more realistic operational conditions where
selection procedures don't perform as well as in validation studies.

\subsection{Star Performer Approach (Joo et al.,
2022)}\label{star-performer-approach-joo-et-al.-2022}

Recognizing heavy-tailed performance distributions dramatically
increases utility estimates:

\begin{itemize}
\tightlist
\item
  \textbf{Star-Adjusted Total Utility:} \$308,928,370
\item
  \textbf{Improvement over Traditional:} \$196,669,435 (+175\%)
\item
  \textbf{SDy Multiplier:} 2.75× (from \$11,600 to \$31,900)
\end{itemize}

This approach acknowledges that top performers can create value far
exceeding normal distribution assumptions.

\subsection{Combined Approach: Realistic Star
Recognition}\label{combined-approach-realistic-star-recognition}

The most balanced approach combines Sturman's caution with star
performer recognition:

\begin{itemize}
\tightlist
\item
  \textbf{Combined Total Utility:} \$247,142,696
\item
  \textbf{Net Improvement over Traditional:} \$134,883,761 (+120\%)
\item
  \textbf{Adjustment Factor:} 20\% reduction (less severe than Sturman
  alone)
\end{itemize}

This represents the most realistic scenario, acknowledging both
operational constraints and exceptional performer value.

\section{Strategic Implications}\label{strategic-implications}

\subsection{Investment Justification}\label{investment-justification}

Even under the most conservative (Sturman-adjusted) scenario, the
selection program generates \textbf{\$72,968,307} in value, representing
a substantial return on investment. The total assessment costs were only
\textbf{\$123,600}.

\subsection{Risk-Return Analysis}\label{risk-return-analysis}

\begin{longtable}[t]{llrl}
\caption{\label{tab:risk-return-table}Risk-Return Analysis of Selection Program Investment}\\
\toprule
Scenario & Total Utility & ROI Multiple & Probability\\
\midrule
Conservative (Sturman) & \$72,968,307 & 590 & High\\
Realistic (Combined) & \$247,142,696 & 2000 & Medium-High\\
Optimistic (Star Power) & \$308,928,370 & 2499 & Medium\\
\bottomrule
\end{longtable}

\subsection{Practical Recommendations}\label{practical-recommendations}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Selection Program Justification:} All scenarios support
  substantial investment in high-validity selection procedures
\item
  \textbf{Star Performer Focus:} Organizations should design selection
  systems specifically to identify potential star performers
\item
  \textbf{Long-term Perspective:} The 10-year time horizon demonstrates
  the cumulative value of good selection decisions
\item
  \textbf{Risk Management:} Even conservative estimates provide strong
  business cases for selection program investment
\end{enumerate}

\section{Research Evolution and Future
Directions}\label{research-evolution-and-future-directions}

\subsection{Historical Progression}\label{historical-progression}

The evolution of utility analysis demonstrates increasing
sophistication:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{1940s-1980s:} Basic utility models established theoretical
  foundation
\item
  \textbf{2000s:} Sturman and others added realism and caution
\item
  \textbf{2020s:} Star performer research recognizes exceptional value
  creation
\end{enumerate}

\subsection{Future Research Needs}\label{future-research-needs}

\begin{itemize}
\tightlist
\item
  \textbf{Dynamic utility models} accounting for changing job
  requirements
\item
  \textbf{Machine learning applications} for identifying star performer
  potential\\
\item
  \textbf{Organizational context effects} on utility realization
\item
  \textbf{Cross-cultural validation} of star performer phenomena
\end{itemize}

\section{Conclusions}\label{conclusions}

This comprehensive analysis of the Latham \& Whyte case demonstrates
that methodological advances in utility analysis provide increasingly
nuanced insights into selection program value. While traditional
approaches may overestimate benefits, the recognition of star performers
suggests that high-quality selection programs create even greater value
than originally thought.

\textbf{Key Takeaways:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Traditional utility analysis} provides a useful baseline but
  may overestimate benefits
\item
  \textbf{Sturman's adjustments} add necessary realism about operational
  constraints\\
\item
  \textbf{Star performer recognition} reveals the exceptional value of
  top talent
\item
  \textbf{Combined approaches} offer the most balanced and realistic
  assessments
\end{enumerate}

The evidence strongly supports continued investment in high-validity
selection procedures, particularly those designed to identify potential
star performers. Even under conservative assumptions, the return on
investment remains compelling.

\section{References}\label{references}

Burke, M. J., \& Frederick, J. T. (1986). A comparison of economic
utility estimates for alternative SDy estimation procedures.
\emph{Journal of Applied Psychology}, 71(2), 334-339.

Joo, H., Aguinis, H., \& Bradley, K. J. (2022). HRM's role in the
financial value of firms obtaining more stars. \emph{The International
Journal of Human Resource Management}, 33(1), 4173-4216.

Latham, G. P., \& Whyte, G. (1994). The futility of utility analysis.
\emph{Personnel Psychology}, 47(1), 31-46.

Sturman, M. C. (2000). Implications of utility analysis adjustments for
estimates of human resource intervention value. \emph{Journal of
Management}, 26(2), 281-299.

Sturman, M. C., Trevor, C. O., Boudreau, J. W., \& Gerhart, B. (2003).
Is it worth it to win the talent war? Evaluating the utility of
performance-based pay. \emph{Personnel Psychology}, 56(4), 997-1035.

Sturman, M. C., Côté, S., \& Mangum, T. W. (2023). Getting more from
stars: A commentary on Joo, Aguinis, and Bradley (2022). \emph{The
International Journal of Human Resource Management}, 34(14), 2747-2760.

\end{document}
